// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.4
// source: src/client-stream/client.proto

package client_stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	server_stream "src/server-stream"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackAcceleration int32

const (
	PlaybackAcceleration_MaintainSpeed PlaybackAcceleration = 0
	PlaybackAcceleration_Faster        PlaybackAcceleration = 1
	PlaybackAcceleration_Slower        PlaybackAcceleration = 2
)

// Enum value maps for PlaybackAcceleration.
var (
	PlaybackAcceleration_name = map[int32]string{
		0: "MaintainSpeed",
		1: "Faster",
		2: "Slower",
	}
	PlaybackAcceleration_value = map[string]int32{
		"MaintainSpeed": 0,
		"Faster":        1,
		"Slower":        2,
	}
)

func (x PlaybackAcceleration) Enum() *PlaybackAcceleration {
	p := new(PlaybackAcceleration)
	*p = x
	return p
}

func (x PlaybackAcceleration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackAcceleration) Descriptor() protoreflect.EnumDescriptor {
	return file_src_client_stream_client_proto_enumTypes[0].Descriptor()
}

func (PlaybackAcceleration) Type() protoreflect.EnumType {
	return &file_src_client_stream_client_proto_enumTypes[0]
}

func (x PlaybackAcceleration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackAcceleration.Descriptor instead.
func (PlaybackAcceleration) EnumDescriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{0}
}

type VideoConfigLive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraId   int32 `protobuf:"varint,1,opt,name=cameraId,proto3" json:"cameraId,omitempty"`
	Resolution int32 `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
}

func (x *VideoConfigLive) Reset() {
	*x = VideoConfigLive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoConfigLive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConfigLive) ProtoMessage() {}

func (x *VideoConfigLive) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConfigLive.ProtoReflect.Descriptor instead.
func (*VideoConfigLive) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{0}
}

func (x *VideoConfigLive) GetCameraId() int32 {
	if x != nil {
		return x.CameraId
	}
	return 0
}

func (x *VideoConfigLive) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

type VideoConfigArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchiveId            int32                `protobuf:"varint,1,opt,name=archiveId,proto3" json:"archiveId,omitempty"`
	Resolution           int32                `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	PlaybackAcceleration PlaybackAcceleration `protobuf:"varint,3,opt,name=playbackAcceleration,proto3,enum=PlaybackAcceleration" json:"playbackAcceleration,omitempty"`
	FromSecond           *int32               `protobuf:"varint,4,opt,name=fromSecond,proto3,oneof" json:"fromSecond,omitempty"`
}

func (x *VideoConfigArchive) Reset() {
	*x = VideoConfigArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoConfigArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConfigArchive) ProtoMessage() {}

func (x *VideoConfigArchive) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConfigArchive.ProtoReflect.Descriptor instead.
func (*VideoConfigArchive) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{1}
}

func (x *VideoConfigArchive) GetArchiveId() int32 {
	if x != nil {
		return x.ArchiveId
	}
	return 0
}

func (x *VideoConfigArchive) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *VideoConfigArchive) GetPlaybackAcceleration() PlaybackAcceleration {
	if x != nil {
		return x.PlaybackAcceleration
	}
	return PlaybackAcceleration_MaintainSpeed
}

func (x *VideoConfigArchive) GetFromSecond() int32 {
	if x != nil && x.FromSecond != nil {
		return *x.FromSecond
	}
	return 0
}

type ArchiveListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *ArchivedVideoFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize   int32                `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageOffset int32                `protobuf:"varint,3,opt,name=pageOffset,proto3" json:"pageOffset,omitempty"`
}

func (x *ArchiveListRequest) Reset() {
	*x = ArchiveListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveListRequest) ProtoMessage() {}

func (x *ArchiveListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveListRequest.ProtoReflect.Descriptor instead.
func (*ArchiveListRequest) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{2}
}

func (x *ArchiveListRequest) GetFilter() *ArchivedVideoFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ArchiveListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArchiveListRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

type ArchiveListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSize int32                     `protobuf:"varint,1,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	FromIndex int32                     `protobuf:"varint,2,opt,name=fromIndex,proto3" json:"fromIndex,omitempty"`
	ToIndex   int32                     `protobuf:"varint,3,opt,name=toIndex,proto3" json:"toIndex,omitempty"`
	Config    []*ArchivedEntityMetaInfo `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty"`
}

func (x *ArchiveListResponse) Reset() {
	*x = ArchiveListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveListResponse) ProtoMessage() {}

func (x *ArchiveListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveListResponse.ProtoReflect.Descriptor instead.
func (*ArchiveListResponse) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{3}
}

func (x *ArchiveListResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ArchiveListResponse) GetFromIndex() int32 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

func (x *ArchiveListResponse) GetToIndex() int32 {
	if x != nil {
		return x.ToIndex
	}
	return 0
}

func (x *ArchiveListResponse) GetConfig() []*ArchivedEntityMetaInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

type ArchivedVideoFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainsMotions bool                   `protobuf:"varint,1,opt,name=containsMotions,proto3" json:"containsMotions,omitempty"`
	StartDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *ArchivedVideoFilter) Reset() {
	*x = ArchivedVideoFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivedVideoFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivedVideoFilter) ProtoMessage() {}

func (x *ArchivedVideoFilter) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivedVideoFilter.ProtoReflect.Descriptor instead.
func (*ArchivedVideoFilter) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{4}
}

func (x *ArchivedVideoFilter) GetContainsMotions() bool {
	if x != nil {
		return x.ContainsMotions
	}
	return false
}

func (x *ArchivedVideoFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ArchivedVideoFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ArchivedEntityMetaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter        *ArchivedVideoFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	MaxResolution int32                `protobuf:"varint,3,opt,name=maxResolution,proto3" json:"maxResolution,omitempty"`
}

func (x *ArchivedEntityMetaInfo) Reset() {
	*x = ArchivedEntityMetaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivedEntityMetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivedEntityMetaInfo) ProtoMessage() {}

func (x *ArchivedEntityMetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivedEntityMetaInfo.ProtoReflect.Descriptor instead.
func (*ArchivedEntityMetaInfo) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{5}
}

func (x *ArchivedEntityMetaInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArchivedEntityMetaInfo) GetFilter() *ArchivedVideoFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ArchivedEntityMetaInfo) GetMaxResolution() int32 {
	if x != nil {
		return x.MaxResolution
	}
	return 0
}

type CameraList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cameras []*CameraInfo `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
}

func (x *CameraList) Reset() {
	*x = CameraList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraList) ProtoMessage() {}

func (x *CameraList) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraList.ProtoReflect.Descriptor instead.
func (*CameraList) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{6}
}

func (x *CameraList) GetCameras() []*CameraInfo {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type CameraInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *CameraInfo) Reset() {
	*x = CameraInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_client_stream_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInfo) ProtoMessage() {}

func (x *CameraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_client_stream_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInfo.ProtoReflect.Descriptor instead.
func (*CameraInfo) Descriptor() ([]byte, []int) {
	return file_src_client_stream_client_proto_rawDescGZIP(), []int{7}
}

func (x *CameraInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CameraInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_src_client_stream_client_proto protoreflect.FileDescriptor

var file_src_client_stream_client_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x73, 0x72, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d,
	0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x76,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd1, 0x01,
	0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x63,
	0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x65, 0x6c,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63,
	0x6b, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a,
	0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x22, 0x7e, 0x0a, 0x12, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x9c, 0x01, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x2f, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0xaf, 0x01, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x73, 0x4d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x4d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x7c, 0x0a, 0x16, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61,
	0x78, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x33, 0x0a, 0x0a, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x07, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x63, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x73, 0x22, 0x38, 0x0a, 0x0a, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a,
	0x41, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x65, 0x6c,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x10, 0x02, 0x32, 0x82, 0x02, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0b, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x10, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4c, 0x69, 0x76, 0x65, 0x1a, 0x0b, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x13, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x1a, 0x0b, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x72, 0x63, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_client_stream_client_proto_rawDescOnce sync.Once
	file_src_client_stream_client_proto_rawDescData = file_src_client_stream_client_proto_rawDesc
)

func file_src_client_stream_client_proto_rawDescGZIP() []byte {
	file_src_client_stream_client_proto_rawDescOnce.Do(func() {
		file_src_client_stream_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_client_stream_client_proto_rawDescData)
	})
	return file_src_client_stream_client_proto_rawDescData
}

var file_src_client_stream_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_client_stream_client_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_src_client_stream_client_proto_goTypes = []interface{}{
	(PlaybackAcceleration)(0),        // 0: PlaybackAcceleration
	(*VideoConfigLive)(nil),          // 1: VideoConfigLive
	(*VideoConfigArchive)(nil),       // 2: VideoConfigArchive
	(*ArchiveListRequest)(nil),       // 3: ArchiveListRequest
	(*ArchiveListResponse)(nil),      // 4: ArchiveListResponse
	(*ArchivedVideoFilter)(nil),      // 5: ArchivedVideoFilter
	(*ArchivedEntityMetaInfo)(nil),   // 6: ArchivedEntityMetaInfo
	(*CameraList)(nil),               // 7: CameraList
	(*CameraInfo)(nil),               // 8: CameraInfo
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
	(*server_stream.VideoFrame)(nil), // 11: VideoFrame
}
var file_src_client_stream_client_proto_depIdxs = []int32{
	0,  // 0: VideoConfigArchive.playbackAcceleration:type_name -> PlaybackAcceleration
	5,  // 1: ArchiveListRequest.filter:type_name -> ArchivedVideoFilter
	6,  // 2: ArchiveListResponse.config:type_name -> ArchivedEntityMetaInfo
	9,  // 3: ArchivedVideoFilter.startDate:type_name -> google.protobuf.Timestamp
	9,  // 4: ArchivedVideoFilter.endDate:type_name -> google.protobuf.Timestamp
	5,  // 5: ArchivedEntityMetaInfo.filter:type_name -> ArchivedVideoFilter
	8,  // 6: CameraList.cameras:type_name -> CameraInfo
	10, // 7: ClientVideoStream.GetCameraList:input_type -> google.protobuf.Empty
	3,  // 8: ClientVideoStream.GetArchivedList:input_type -> ArchiveListRequest
	1,  // 9: ClientVideoStream.StreamLiveVideo:input_type -> VideoConfigLive
	2,  // 10: ClientVideoStream.StreamArchivedVideo:input_type -> VideoConfigArchive
	7,  // 11: ClientVideoStream.GetCameraList:output_type -> CameraList
	4,  // 12: ClientVideoStream.GetArchivedList:output_type -> ArchiveListResponse
	11, // 13: ClientVideoStream.StreamLiveVideo:output_type -> VideoFrame
	11, // 14: ClientVideoStream.StreamArchivedVideo:output_type -> VideoFrame
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_src_client_stream_client_proto_init() }
func file_src_client_stream_client_proto_init() {
	if File_src_client_stream_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_client_stream_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoConfigLive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoConfigArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivedVideoFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivedEntityMetaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_client_stream_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_src_client_stream_client_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_client_stream_client_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_client_stream_client_proto_goTypes,
		DependencyIndexes: file_src_client_stream_client_proto_depIdxs,
		EnumInfos:         file_src_client_stream_client_proto_enumTypes,
		MessageInfos:      file_src_client_stream_client_proto_msgTypes,
	}.Build()
	File_src_client_stream_client_proto = out.File
	file_src_client_stream_client_proto_rawDesc = nil
	file_src_client_stream_client_proto_goTypes = nil
	file_src_client_stream_client_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientVideoStreamClient is the client API for ClientVideoStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientVideoStreamClient interface {
	GetCameraList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CameraList, error)
	GetArchivedList(ctx context.Context, in *ArchiveListRequest, opts ...grpc.CallOption) (*ArchiveListResponse, error)
	StreamLiveVideo(ctx context.Context, opts ...grpc.CallOption) (ClientVideoStream_StreamLiveVideoClient, error)
	StreamArchivedVideo(ctx context.Context, opts ...grpc.CallOption) (ClientVideoStream_StreamArchivedVideoClient, error)
}

type clientVideoStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewClientVideoStreamClient(cc grpc.ClientConnInterface) ClientVideoStreamClient {
	return &clientVideoStreamClient{cc}
}

func (c *clientVideoStreamClient) GetCameraList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CameraList, error) {
	out := new(CameraList)
	err := c.cc.Invoke(ctx, "/ClientVideoStream/GetCameraList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientVideoStreamClient) GetArchivedList(ctx context.Context, in *ArchiveListRequest, opts ...grpc.CallOption) (*ArchiveListResponse, error) {
	out := new(ArchiveListResponse)
	err := c.cc.Invoke(ctx, "/ClientVideoStream/GetArchivedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientVideoStreamClient) StreamLiveVideo(ctx context.Context, opts ...grpc.CallOption) (ClientVideoStream_StreamLiveVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClientVideoStream_serviceDesc.Streams[0], "/ClientVideoStream/StreamLiveVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientVideoStreamStreamLiveVideoClient{stream}
	return x, nil
}

type ClientVideoStream_StreamLiveVideoClient interface {
	Send(*VideoConfigLive) error
	Recv() (*server_stream.VideoFrame, error)
	grpc.ClientStream
}

type clientVideoStreamStreamLiveVideoClient struct {
	grpc.ClientStream
}

func (x *clientVideoStreamStreamLiveVideoClient) Send(m *VideoConfigLive) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientVideoStreamStreamLiveVideoClient) Recv() (*server_stream.VideoFrame, error) {
	m := new(server_stream.VideoFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientVideoStreamClient) StreamArchivedVideo(ctx context.Context, opts ...grpc.CallOption) (ClientVideoStream_StreamArchivedVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClientVideoStream_serviceDesc.Streams[1], "/ClientVideoStream/StreamArchivedVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientVideoStreamStreamArchivedVideoClient{stream}
	return x, nil
}

type ClientVideoStream_StreamArchivedVideoClient interface {
	Send(*VideoConfigArchive) error
	Recv() (*server_stream.VideoFrame, error)
	grpc.ClientStream
}

type clientVideoStreamStreamArchivedVideoClient struct {
	grpc.ClientStream
}

func (x *clientVideoStreamStreamArchivedVideoClient) Send(m *VideoConfigArchive) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientVideoStreamStreamArchivedVideoClient) Recv() (*server_stream.VideoFrame, error) {
	m := new(server_stream.VideoFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientVideoStreamServer is the server API for ClientVideoStream service.
type ClientVideoStreamServer interface {
	GetCameraList(context.Context, *emptypb.Empty) (*CameraList, error)
	GetArchivedList(context.Context, *ArchiveListRequest) (*ArchiveListResponse, error)
	StreamLiveVideo(ClientVideoStream_StreamLiveVideoServer) error
	StreamArchivedVideo(ClientVideoStream_StreamArchivedVideoServer) error
}

// UnimplementedClientVideoStreamServer can be embedded to have forward compatible implementations.
type UnimplementedClientVideoStreamServer struct {
}

func (*UnimplementedClientVideoStreamServer) GetCameraList(context.Context, *emptypb.Empty) (*CameraList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCameraList not implemented")
}
func (*UnimplementedClientVideoStreamServer) GetArchivedList(context.Context, *ArchiveListRequest) (*ArchiveListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArchivedList not implemented")
}
func (*UnimplementedClientVideoStreamServer) StreamLiveVideo(ClientVideoStream_StreamLiveVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLiveVideo not implemented")
}
func (*UnimplementedClientVideoStreamServer) StreamArchivedVideo(ClientVideoStream_StreamArchivedVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamArchivedVideo not implemented")
}

func RegisterClientVideoStreamServer(s *grpc.Server, srv ClientVideoStreamServer) {
	s.RegisterService(&_ClientVideoStream_serviceDesc, srv)
}

func _ClientVideoStream_GetCameraList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientVideoStreamServer).GetCameraList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientVideoStream/GetCameraList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientVideoStreamServer).GetCameraList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientVideoStream_GetArchivedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientVideoStreamServer).GetArchivedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientVideoStream/GetArchivedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientVideoStreamServer).GetArchivedList(ctx, req.(*ArchiveListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientVideoStream_StreamLiveVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientVideoStreamServer).StreamLiveVideo(&clientVideoStreamStreamLiveVideoServer{stream})
}

type ClientVideoStream_StreamLiveVideoServer interface {
	Send(*server_stream.VideoFrame) error
	Recv() (*VideoConfigLive, error)
	grpc.ServerStream
}

type clientVideoStreamStreamLiveVideoServer struct {
	grpc.ServerStream
}

func (x *clientVideoStreamStreamLiveVideoServer) Send(m *server_stream.VideoFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientVideoStreamStreamLiveVideoServer) Recv() (*VideoConfigLive, error) {
	m := new(VideoConfigLive)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientVideoStream_StreamArchivedVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientVideoStreamServer).StreamArchivedVideo(&clientVideoStreamStreamArchivedVideoServer{stream})
}

type ClientVideoStream_StreamArchivedVideoServer interface {
	Send(*server_stream.VideoFrame) error
	Recv() (*VideoConfigArchive, error)
	grpc.ServerStream
}

type clientVideoStreamStreamArchivedVideoServer struct {
	grpc.ServerStream
}

func (x *clientVideoStreamStreamArchivedVideoServer) Send(m *server_stream.VideoFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientVideoStreamStreamArchivedVideoServer) Recv() (*VideoConfigArchive, error) {
	m := new(VideoConfigArchive)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ClientVideoStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClientVideoStream",
	HandlerType: (*ClientVideoStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCameraList",
			Handler:    _ClientVideoStream_GetCameraList_Handler,
		},
		{
			MethodName: "GetArchivedList",
			Handler:    _ClientVideoStream_GetArchivedList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLiveVideo",
			Handler:       _ClientVideoStream_StreamLiveVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamArchivedVideo",
			Handler:       _ClientVideoStream_StreamArchivedVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/client-stream/client.proto",
}
